version: "3"

services:

  jenkins:
    container_name: jenkins
    image: magnobiet/jenkins:latest
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data/jenkins:/var/jenkins_home"
